### ISSUE TITLE
GHCL Scores on incomplete data when more than 100 PRs have been raised

### ISSUE THREAD

**Issue by javatarz** [javatarz/github-contribution-leaderboard#28]
**Describe the bug**
Use any user with over 100 PRs and only their oldest 100 PRs are used to evaluate the score

**To Reproduce**
1. Call the script with user `artfuldev`
2. Only 100 PRs are used to calculate score
3. Call `https://api.github.com/search/issues?q=is:pr author:artfuldev archived:false&sort=created&order=asc` and notice the user has 524 PRs

**Expected behavior**
Score should be evaluated based on 524 PRs for this user

**Comment by rahulbagad** [comment]
@javatarz please assign it to me. I'm working on it.
